#!/usr/bin/env node
import { spawn, spawnSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { createServer } from 'vite';
import { packageTeamsApp } from './package-teams-app.mjs';

const root = fileURLToPath(new URL('..', import.meta.url));
const port = 53000;
const host = '127.0.0.1';
const localHttpUrl = `http://${host}:${port}`;
const localHttpsUrl = `https://localhost:${port}`;

const args = new Set(process.argv.slice(2));
const isHttpsAuto = args.has('--https-auto');
const isSetupCert = args.has('--setup-cert');
const isTeams = args.has('--teams');
const isLocalHttp = args.has('--local-http');

if ([isHttpsAuto, isSetupCert, isTeams, isLocalHttp].filter(Boolean).length !== 1) {
  console.error('\n  x Pick exactly one dev mode: --https-auto, --setup-cert, --teams, or --local-http.\n');
  process.exit(1);
}

if (isHttpsAuto || isSetupCert) {
  process.env.BUMPERS_TEAMS_HTTPS = '1';
}

let server;
let tunnelProcess;
let shuttingDown = false;

function errorMessage(error) {
  return error instanceof Error ? error.message : String(error);
}

function hasCommand(command) {
  const result = spawnSync(command, ['--version'], { stdio: 'ignore' });
  return !result.error;
}

function printHttpsRecovery(error) {
  console.error(`\n  x Local HTTPS setup failed: ${errorMessage(error)}`);
  console.error('');
  console.error('  Run the one-time HTTPS setup, then retry dev:');
  console.error('    npm run dev:setup');
  console.error('    npm run dev');
  console.error('');
}

function printDevTunnelInstallHelp() {
  console.error('\n  x Microsoft Dev Tunnels CLI was not found.');
  console.error('');
  console.error('  Install it, then log in:');
  console.error('    macOS:   brew install --cask devtunnel');
  console.error('    Windows: winget install Microsoft.devtunnel');
  console.error('    Script:  curl -sL https://aka.ms/DevTunnelCliInstall | bash');
  console.error('');
  console.error('    devtunnel user login');
  console.error('    npm run dev:teams');
  console.error('');
}

function parseTunnelUrl(output) {
  const match = output.match(/https:\/\/[^\s,]+\.devtunnels\.ms(?::\d+)?\/?/);
  if (!match) return undefined;
  return new URL(match[0]).origin;
}

function resolveManualTunnelUrl(value) {
  try {
    const url = new URL(value);
    if (url.protocol !== 'https:') {
      throw new Error('TEAMS_TUNNEL_URL must start with https://');
    }
    return url.origin;
  } catch (error) {
    console.error(`\n  x Invalid TEAMS_TUNNEL_URL: ${errorMessage(error)}\n`);
    process.exit(1);
  }
}

function writeTeamsEnv(endpoint) {
  const url = new URL(endpoint);
  const envDir = join(root, 'env');
  mkdirSync(envDir, { recursive: true });
  writeFileSync(
    join(envDir, '.env.local'),
    [
      '# Local Teams dev values generated by npm run dev:teams',
      `TAB_ENDPOINT=${url.origin}`,
      `TAB_DOMAIN=${url.hostname}`,
      '',
    ].join('\n'),
  );
}

async function startVite({ https = false } = {}) {
  const viteServer = await createServer({
    server: {
      host: '127.0.0.1',
      port: 53000,
      strictPort: true,
    },
  });
  await viteServer.listen();

  console.log('');
  console.log(`  Vite dev server: ${https ? localHttpsUrl : localHttpUrl}`);
  return viteServer;
}

async function cleanup() {
  if (shuttingDown) return;
  shuttingDown = true;

  if (tunnelProcess && !tunnelProcess.killed) {
    tunnelProcess.kill();
  }

  if (server) {
    await server.close();
  }
}

function waitUntilStopped() {
  return new Promise(() => {
    // Intentionally unresolved. The selected dev server mode runs until SIGINT/SIGTERM.
  });
}

function wireShutdownHandlers() {
  for (const signal of ['SIGINT', 'SIGTERM']) {
    process.on(signal, async () => {
      await cleanup();
      process.exit(0);
    });
  }
}

function printTeamsSummary(endpoint, packagePath) {
  console.log('');
  console.log(`  Local URL: ${localHttpUrl}`);
  console.log(`  Teams URL: ${endpoint}`);
  console.log(`  Teams package: ${packagePath}`);
  console.log('');
  console.log('  Upload it in Teams:');
  console.log('    Apps -> Manage your apps -> Upload a custom app');
  console.log('');
  console.log('  Warning: this uses anonymous tunnel access.');
  console.log('  Anyone with the tunnel URL can reach your local dev server while this is running.');
  console.log('');
}

async function runLocalHttp() {
  wireShutdownHandlers();
  server = await startVite();
  await waitUntilStopped();
}

async function runHttpsAuto() {
  wireShutdownHandlers();
  try {
    server = await startVite({ https: true });
    await waitUntilStopped();
  } catch (error) {
    await cleanup();
    printHttpsRecovery(error);
    process.exit(1);
  }
}

async function runSetupCert() {
  try {
    server = await startVite({ https: true });
    await server.close();
    server = undefined;
    console.log('');
    console.log('  Local HTTPS certificate setup completed.');
    console.log('  Now run `npm run dev`.');
    console.log('');
  } catch (error) {
    await cleanup();
    console.error(`\n  x Local HTTPS certificate setup failed: ${errorMessage(error)}`);
    console.error('');
    console.error('  Fix the certificate/bootstrap issue, then run:');
    console.error('    npm run dev:setup');
    console.error('');
    process.exit(1);
  }
}

function startDevTunnel() {
  return new Promise((resolve, reject) => {
    let output = '';
    let resolved = false;

    tunnelProcess = spawn('devtunnel', ['host', '-p', String(port), '--allow-anonymous', '--protocol', 'http'], {
      cwd: root,
      stdio: ['ignore', 'pipe', 'pipe'],
    });

    function handleOutput(chunk) {
      const text = chunk.toString();
      output += text;
      process.stdout.write(text);

      const endpoint = parseTunnelUrl(output);
      if (endpoint && !resolved) {
        resolved = true;
        resolve(endpoint);
      }
    }

    tunnelProcess.stdout.on('data', handleOutput);
    tunnelProcess.stderr.on('data', handleOutput);

    tunnelProcess.on('error', reject);
    tunnelProcess.on('exit', (code) => {
      if (shuttingDown) return;

      const authHint =
        output.toLowerCase().includes('login') ||
        output.toLowerCase().includes('not logged in') ||
        output.toLowerCase().includes('unauthorized');

      if (!resolved) {
        if (authHint) {
          reject(new Error('Dev Tunnels login is required. Run: devtunnel user login'));
        } else {
          reject(new Error(`devtunnel exited before publishing a tunnel URL${code === null ? '' : ` (exit ${code})`}.`));
        }
        return;
      }

      cleanup().then(() => process.exit(code ?? 1));
    });
  });
}

async function runTeams(manualTunnelUrl) {
  if (!manualTunnelUrl && !hasCommand('devtunnel')) {
    printDevTunnelInstallHelp();
    process.exit(1);
  }

  wireShutdownHandlers();
  server = await startVite();

  try {
    const endpoint =
      manualTunnelUrl
        ? resolveManualTunnelUrl(manualTunnelUrl)
        : await startDevTunnel();

    writeTeamsEnv(endpoint);
    const { packagePath } = packageTeamsApp({ quiet: true });
    printTeamsSummary(endpoint, packagePath);
    await waitUntilStopped();
  } catch (error) {
    await cleanup();
    console.error(`\n  x ${errorMessage(error)}`);
    if (errorMessage(error).toLowerCase().includes('login')) {
      console.error('');
      console.error('    devtunnel user login');
      console.error('    npm run dev:teams');
    }
    console.error('');
    process.exit(1);
  }
}

if (isHttpsAuto) {
  await runHttpsAuto();
} else if (isSetupCert) {
  await runSetupCert();
} else if (isTeams) {
  await runTeams(process.env.TEAMS_TUNNEL_URL);
} else {
  await runLocalHttp();
}
